-- Initial schema for the racing-game-backend MVP.
--
-- Conventions:
--   * UUID primary keys generated by gen_random_uuid() (pgcrypto).
--   * created_at / updated_at timestamps maintained by the application
--     or trigger. The trigger is defined once here and reused.
--   * No real-time car positions are stored here. Real-time state lives
--     in Game Server memory (Spec 09 future).

BEGIN;

CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- Reusable updated_at trigger. Each table that needs it gets its own
-- trigger because PostgreSQL triggers can't share function bodies
-- across tables with different column sets via a single definition.
CREATE OR REPLACE FUNCTION set_updated_at() RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- ─── users ───────────────────────────────────────────────────────────
-- Auth identity. Players may have NULL password_hash for guest accounts.
CREATE TABLE IF NOT EXISTS users (
    id            UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
    email         TEXT        UNIQUE,
    password_hash TEXT,
    is_guest      BOOLEAN     NOT NULL DEFAULT FALSE,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at    TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TRIGGER trg_users_updated_at
    BEFORE UPDATE ON users
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- ─── players ─────────────────────────────────────────────────────────
-- Game profile tied to a user. Display name is the in-game identity.
CREATE TABLE IF NOT EXISTS players (
    id           UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id      UUID        NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    display_name TEXT        NOT NULL,
    created_at   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at   TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_players_user_id ON players(user_id);

CREATE TRIGGER trg_players_updated_at
    BEFORE UPDATE ON players
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- ─── cars (global catalog) ───────────────────────────────────────────
-- The set of car models that exist in the game.
CREATE TABLE IF NOT EXISTS cars (
    id          UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
    name        TEXT        NOT NULL UNIQUE,
    base_stats  JSONB       NOT NULL DEFAULT '{}'::jsonb,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ─── player_cars ─────────────────────────────────────────────────────
-- Ownership and customization of cars per player.
CREATE TABLE IF NOT EXISTS player_cars (
    id            UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
    player_id     UUID        NOT NULL REFERENCES players(id) ON DELETE CASCADE,
    car_id        UUID        NOT NULL REFERENCES cars(id)    ON DELETE RESTRICT,
    acquired_at   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    customizations JSONB      NOT NULL DEFAULT '{}'::jsonb,
    UNIQUE (player_id, car_id)
);

CREATE INDEX IF NOT EXISTS idx_player_cars_player_id ON player_cars(player_id);

-- ─── tracks (catalog) ────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS tracks (
    id         UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
    name       TEXT        NOT NULL UNIQUE,
    layout     JSONB       NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ─── races (metadata only) ───────────────────────────────────────────
-- status moves through: pending → in_progress → finished → cancelled.
CREATE TABLE IF NOT EXISTS races (
    id          UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
    track_id    UUID        NOT NULL REFERENCES tracks(id) ON DELETE RESTRICT,
    status      TEXT        NOT NULL DEFAULT 'pending'
                            CHECK (status IN ('pending','in_progress','finished','cancelled')),
    started_at  TIMESTAMPTZ,
    finished_at TIMESTAMPTZ,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_races_track_id ON races(track_id);
CREATE INDEX IF NOT EXISTS idx_races_status   ON races(status);

-- ─── race_players (participation) ────────────────────────────────────
CREATE TABLE IF NOT EXISTS race_players (
    id              UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
    race_id         UUID        NOT NULL REFERENCES races(id)   ON DELETE CASCADE,
    player_id       UUID        NOT NULL REFERENCES players(id) ON DELETE CASCADE,
    finish_position INT,
    finished_at     TIMESTAMPTZ,
    UNIQUE (race_id, player_id)
);

CREATE INDEX IF NOT EXISTS idx_race_players_race_id   ON race_players(race_id);
CREATE INDEX IF NOT EXISTS idx_race_players_player_id ON race_players(player_id);

-- ─── race_results (final per-player result) ──────────────────────────
CREATE TABLE IF NOT EXISTS race_results (
    id             UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
    race_id        UUID        NOT NULL REFERENCES races(id)   ON DELETE CASCADE,
    player_id      UUID        NOT NULL REFERENCES players(id) ON DELETE CASCADE,
    position       INT         NOT NULL,
    total_time_ms  INT         NOT NULL,
    best_lap_ms    INT,
    created_at     TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE (race_id, player_id)
);

CREATE INDEX IF NOT EXISTS idx_race_results_race_id    ON race_results(race_id);
CREATE INDEX IF NOT EXISTS idx_race_results_player_id  ON race_results(player_id);
CREATE INDEX IF NOT EXISTS idx_race_results_position   ON race_results(position);

COMMIT;