// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v5.29.3
// source: game.proto

// Wire contract between the Go Game Server and the Unity mobile
// client. Future game-state traffic (race sync, events) flows over
// UDP using these messages.
//
// Conventions:
//   * Field tags are frozen — never reorder, never reuse.
//   * Field names use lower_snake_case in proto, exposed as
//     CamelCase in Go and C#.
//   * No PII or auth tokens here — those belong in REST/JWT only.

package gamepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Vector3 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             float32                `protobuf:"fixed32,1,opt,name=x,proto3" json:"x,omitempty"`
	Y             float32                `protobuf:"fixed32,2,opt,name=y,proto3" json:"y,omitempty"`
	Z             float32                `protobuf:"fixed32,3,opt,name=z,proto3" json:"z,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Vector3) Reset() {
	*x = Vector3{}
	mi := &file_game_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Vector3) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Vector3) ProtoMessage() {}

func (x *Vector3) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Vector3.ProtoReflect.Descriptor instead.
func (*Vector3) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{0}
}

func (x *Vector3) GetX() float32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Vector3) GetY() float32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *Vector3) GetZ() float32 {
	if x != nil {
		return x.Z
	}
	return 0
}

type Quaternion struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             float32                `protobuf:"fixed32,1,opt,name=x,proto3" json:"x,omitempty"`
	Y             float32                `protobuf:"fixed32,2,opt,name=y,proto3" json:"y,omitempty"`
	Z             float32                `protobuf:"fixed32,3,opt,name=z,proto3" json:"z,omitempty"`
	W             float32                `protobuf:"fixed32,4,opt,name=w,proto3" json:"w,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Quaternion) Reset() {
	*x = Quaternion{}
	mi := &file_game_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Quaternion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Quaternion) ProtoMessage() {}

func (x *Quaternion) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Quaternion.ProtoReflect.Descriptor instead.
func (*Quaternion) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{1}
}

func (x *Quaternion) GetX() float32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Quaternion) GetY() float32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *Quaternion) GetZ() float32 {
	if x != nil {
		return x.Z
	}
	return 0
}

func (x *Quaternion) GetW() float32 {
	if x != nil {
		return x.W
	}
	return 0
}

// Sent by Unity when it opens a UDP connection to the Game Server
// after matchmaking.
type JoinRaceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MatchId       string                 `protobuf:"bytes,1,opt,name=match_id,json=matchId,proto3" json:"match_id,omitempty"`
	PlayerId      string                 `protobuf:"bytes,2,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	GameToken     string                 `protobuf:"bytes,3,opt,name=game_token,json=gameToken,proto3" json:"game_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinRaceRequest) Reset() {
	*x = JoinRaceRequest{}
	mi := &file_game_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinRaceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinRaceRequest) ProtoMessage() {}

func (x *JoinRaceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinRaceRequest.ProtoReflect.Descriptor instead.
func (*JoinRaceRequest) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{2}
}

func (x *JoinRaceRequest) GetMatchId() string {
	if x != nil {
		return x.MatchId
	}
	return ""
}

func (x *JoinRaceRequest) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *JoinRaceRequest) GetGameToken() string {
	if x != nil {
		return x.GameToken
	}
	return ""
}

// Server response. `ok=true` means the player may proceed; `error`
// carries a human-readable reason when ok=false.
type JoinRaceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	RaceId        string                 `protobuf:"bytes,3,opt,name=race_id,json=raceId,proto3" json:"race_id,omitempty"`
	InitialTick   uint64                 `protobuf:"varint,4,opt,name=initial_tick,json=initialTick,proto3" json:"initial_tick,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinRaceResponse) Reset() {
	*x = JoinRaceResponse{}
	mi := &file_game_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinRaceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinRaceResponse) ProtoMessage() {}

func (x *JoinRaceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinRaceResponse.ProtoReflect.Descriptor instead.
func (*JoinRaceResponse) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{3}
}

func (x *JoinRaceResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *JoinRaceResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *JoinRaceResponse) GetRaceId() string {
	if x != nil {
		return x.RaceId
	}
	return ""
}

func (x *JoinRaceResponse) GetInitialTick() uint64 {
	if x != nil {
		return x.InitialTick
	}
	return 0
}

type RaceStarting struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StartTick     uint64                 `protobuf:"varint,1,opt,name=start_tick,json=startTick,proto3" json:"start_tick,omitempty"`
	CountdownMs   uint32                 `protobuf:"varint,2,opt,name=countdown_ms,json=countdownMs,proto3" json:"countdown_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RaceStarting) Reset() {
	*x = RaceStarting{}
	mi := &file_game_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RaceStarting) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RaceStarting) ProtoMessage() {}

func (x *RaceStarting) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RaceStarting.ProtoReflect.Descriptor instead.
func (*RaceStarting) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{4}
}

func (x *RaceStarting) GetStartTick() uint64 {
	if x != nil {
		return x.StartTick
	}
	return 0
}

func (x *RaceStarting) GetCountdownMs() uint32 {
	if x != nil {
		return x.CountdownMs
	}
	return 0
}

type RaceStarted struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StartTick     uint64                 `protobuf:"varint,1,opt,name=start_tick,json=startTick,proto3" json:"start_tick,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RaceStarted) Reset() {
	*x = RaceStarted{}
	mi := &file_game_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RaceStarted) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RaceStarted) ProtoMessage() {}

func (x *RaceStarted) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RaceStarted.ProtoReflect.Descriptor instead.
func (*RaceStarted) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{5}
}

func (x *RaceStarted) GetStartTick() uint64 {
	if x != nil {
		return x.StartTick
	}
	return 0
}

// Sent by Unity on every input tick. Server validates / integrates.
type PlayerInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sequence      uint32                 `protobuf:"varint,1,opt,name=sequence,proto3" json:"sequence,omitempty"`
	Throttle      float32                `protobuf:"fixed32,2,opt,name=throttle,proto3" json:"throttle,omitempty"`
	Brake         float32                `protobuf:"fixed32,3,opt,name=brake,proto3" json:"brake,omitempty"`
	Steering      float32                `protobuf:"fixed32,4,opt,name=steering,proto3" json:"steering,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerInput) Reset() {
	*x = PlayerInput{}
	mi := &file_game_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerInput) ProtoMessage() {}

func (x *PlayerInput) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerInput.ProtoReflect.Descriptor instead.
func (*PlayerInput) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{6}
}

func (x *PlayerInput) GetSequence() uint32 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *PlayerInput) GetThrottle() float32 {
	if x != nil {
		return x.Throttle
	}
	return 0
}

func (x *PlayerInput) GetBrake() float32 {
	if x != nil {
		return x.Brake
	}
	return 0
}

func (x *PlayerInput) GetSteering() float32 {
	if x != nil {
		return x.Steering
	}
	return 0
}

// Per-car snapshot published by the server.
type CarState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      string                 `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	Position      *Vector3               `protobuf:"bytes,2,opt,name=position,proto3" json:"position,omitempty"`
	Rotation      *Quaternion            `protobuf:"bytes,3,opt,name=rotation,proto3" json:"rotation,omitempty"`
	Velocity      *Vector3               `protobuf:"bytes,4,opt,name=velocity,proto3" json:"velocity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CarState) Reset() {
	*x = CarState{}
	mi := &file_game_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CarState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CarState) ProtoMessage() {}

func (x *CarState) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CarState.ProtoReflect.Descriptor instead.
func (*CarState) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{7}
}

func (x *CarState) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *CarState) GetPosition() *Vector3 {
	if x != nil {
		return x.Position
	}
	return nil
}

func (x *CarState) GetRotation() *Quaternion {
	if x != nil {
		return x.Rotation
	}
	return nil
}

func (x *CarState) GetVelocity() *Vector3 {
	if x != nil {
		return x.Velocity
	}
	return nil
}

// Snapshot of every car in the race. Sent at the configured tick rate.
type WorldSnapshot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tick          uint64                 `protobuf:"varint,1,opt,name=tick,proto3" json:"tick,omitempty"`
	Cars          []*CarState            `protobuf:"bytes,2,rep,name=cars,proto3" json:"cars,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorldSnapshot) Reset() {
	*x = WorldSnapshot{}
	mi := &file_game_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorldSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorldSnapshot) ProtoMessage() {}

func (x *WorldSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorldSnapshot.ProtoReflect.Descriptor instead.
func (*WorldSnapshot) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{8}
}

func (x *WorldSnapshot) GetTick() uint64 {
	if x != nil {
		return x.Tick
	}
	return 0
}

func (x *WorldSnapshot) GetCars() []*CarState {
	if x != nil {
		return x.Cars
	}
	return nil
}

type CheckpointPassed struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	PlayerId        string                 `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	CheckpointIndex uint32                 `protobuf:"varint,2,opt,name=checkpoint_index,json=checkpointIndex,proto3" json:"checkpoint_index,omitempty"`
	Tick            uint64                 `protobuf:"varint,3,opt,name=tick,proto3" json:"tick,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CheckpointPassed) Reset() {
	*x = CheckpointPassed{}
	mi := &file_game_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckpointPassed) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckpointPassed) ProtoMessage() {}

func (x *CheckpointPassed) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckpointPassed.ProtoReflect.Descriptor instead.
func (*CheckpointPassed) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{9}
}

func (x *CheckpointPassed) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *CheckpointPassed) GetCheckpointIndex() uint32 {
	if x != nil {
		return x.CheckpointIndex
	}
	return 0
}

func (x *CheckpointPassed) GetTick() uint64 {
	if x != nil {
		return x.Tick
	}
	return 0
}

type LapCompleted struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      string                 `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	Lap           uint32                 `protobuf:"varint,2,opt,name=lap,proto3" json:"lap,omitempty"`
	LapTimeMs     uint32                 `protobuf:"varint,3,opt,name=lap_time_ms,json=lapTimeMs,proto3" json:"lap_time_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LapCompleted) Reset() {
	*x = LapCompleted{}
	mi := &file_game_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LapCompleted) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LapCompleted) ProtoMessage() {}

func (x *LapCompleted) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LapCompleted.ProtoReflect.Descriptor instead.
func (*LapCompleted) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{10}
}

func (x *LapCompleted) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *LapCompleted) GetLap() uint32 {
	if x != nil {
		return x.Lap
	}
	return 0
}

func (x *LapCompleted) GetLapTimeMs() uint32 {
	if x != nil {
		return x.LapTimeMs
	}
	return 0
}

type RaceFinished struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RaceId        string                 `protobuf:"bytes,1,opt,name=race_id,json=raceId,proto3" json:"race_id,omitempty"`
	Results       []*RaceResult          `protobuf:"bytes,2,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RaceFinished) Reset() {
	*x = RaceFinished{}
	mi := &file_game_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RaceFinished) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RaceFinished) ProtoMessage() {}

func (x *RaceFinished) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RaceFinished.ProtoReflect.Descriptor instead.
func (*RaceFinished) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{11}
}

func (x *RaceFinished) GetRaceId() string {
	if x != nil {
		return x.RaceId
	}
	return ""
}

func (x *RaceFinished) GetResults() []*RaceResult {
	if x != nil {
		return x.Results
	}
	return nil
}

type RaceResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      string                 `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	Position      uint32                 `protobuf:"varint,2,opt,name=position,proto3" json:"position,omitempty"`
	TotalTimeMs   uint32                 `protobuf:"varint,3,opt,name=total_time_ms,json=totalTimeMs,proto3" json:"total_time_ms,omitempty"`
	BestLapMs     uint32                 `protobuf:"varint,4,opt,name=best_lap_ms,json=bestLapMs,proto3" json:"best_lap_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RaceResult) Reset() {
	*x = RaceResult{}
	mi := &file_game_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RaceResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RaceResult) ProtoMessage() {}

func (x *RaceResult) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RaceResult.ProtoReflect.Descriptor instead.
func (*RaceResult) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{12}
}

func (x *RaceResult) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *RaceResult) GetPosition() uint32 {
	if x != nil {
		return x.Position
	}
	return 0
}

func (x *RaceResult) GetTotalTimeMs() uint32 {
	if x != nil {
		return x.TotalTimeMs
	}
	return 0
}

func (x *RaceResult) GetBestLapMs() uint32 {
	if x != nil {
		return x.BestLapMs
	}
	return 0
}

type PlayerDisconnected struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      string                 `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerDisconnected) Reset() {
	*x = PlayerDisconnected{}
	mi := &file_game_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerDisconnected) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerDisconnected) ProtoMessage() {}

func (x *PlayerDisconnected) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerDisconnected.ProtoReflect.Descriptor instead.
func (*PlayerDisconnected) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{13}
}

func (x *PlayerDisconnected) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *PlayerDisconnected) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

var File_game_proto protoreflect.FileDescriptor

const file_game_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"game.proto\x12\x0eracing.game.v1\"3\n" +
	"\aVector3\x12\f\n" +
	"\x01x\x18\x01 \x01(\x02R\x01x\x12\f\n" +
	"\x01y\x18\x02 \x01(\x02R\x01y\x12\f\n" +
	"\x01z\x18\x03 \x01(\x02R\x01z\"D\n" +
	"\n" +
	"Quaternion\x12\f\n" +
	"\x01x\x18\x01 \x01(\x02R\x01x\x12\f\n" +
	"\x01y\x18\x02 \x01(\x02R\x01y\x12\f\n" +
	"\x01z\x18\x03 \x01(\x02R\x01z\x12\f\n" +
	"\x01w\x18\x04 \x01(\x02R\x01w\"h\n" +
	"\x0fJoinRaceRequest\x12\x19\n" +
	"\bmatch_id\x18\x01 \x01(\tR\amatchId\x12\x1b\n" +
	"\tplayer_id\x18\x02 \x01(\tR\bplayerId\x12\x1d\n" +
	"\n" +
	"game_token\x18\x03 \x01(\tR\tgameToken\"t\n" +
	"\x10JoinRaceResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12\x17\n" +
	"\arace_id\x18\x03 \x01(\tR\x06raceId\x12!\n" +
	"\finitial_tick\x18\x04 \x01(\x04R\vinitialTick\"P\n" +
	"\fRaceStarting\x12\x1d\n" +
	"\n" +
	"start_tick\x18\x01 \x01(\x04R\tstartTick\x12!\n" +
	"\fcountdown_ms\x18\x02 \x01(\rR\vcountdownMs\",\n" +
	"\vRaceStarted\x12\x1d\n" +
	"\n" +
	"start_tick\x18\x01 \x01(\x04R\tstartTick\"w\n" +
	"\vPlayerInput\x12\x1a\n" +
	"\bsequence\x18\x01 \x01(\rR\bsequence\x12\x1a\n" +
	"\bthrottle\x18\x02 \x01(\x02R\bthrottle\x12\x14\n" +
	"\x05brake\x18\x03 \x01(\x02R\x05brake\x12\x1a\n" +
	"\bsteering\x18\x04 \x01(\x02R\bsteering\"\xc9\x01\n" +
	"\bCarState\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\tR\bplayerId\x123\n" +
	"\bposition\x18\x02 \x01(\v2\x17.racing.game.v1.Vector3R\bposition\x126\n" +
	"\brotation\x18\x03 \x01(\v2\x1a.racing.game.v1.QuaternionR\brotation\x123\n" +
	"\bvelocity\x18\x04 \x01(\v2\x17.racing.game.v1.Vector3R\bvelocity\"Q\n" +
	"\rWorldSnapshot\x12\x12\n" +
	"\x04tick\x18\x01 \x01(\x04R\x04tick\x12,\n" +
	"\x04cars\x18\x02 \x03(\v2\x18.racing.game.v1.CarStateR\x04cars\"n\n" +
	"\x10CheckpointPassed\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\tR\bplayerId\x12)\n" +
	"\x10checkpoint_index\x18\x02 \x01(\rR\x0fcheckpointIndex\x12\x12\n" +
	"\x04tick\x18\x03 \x01(\x04R\x04tick\"]\n" +
	"\fLapCompleted\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\tR\bplayerId\x12\x10\n" +
	"\x03lap\x18\x02 \x01(\rR\x03lap\x12\x1e\n" +
	"\vlap_time_ms\x18\x03 \x01(\rR\tlapTimeMs\"]\n" +
	"\fRaceFinished\x12\x17\n" +
	"\arace_id\x18\x01 \x01(\tR\x06raceId\x124\n" +
	"\aresults\x18\x02 \x03(\v2\x1a.racing.game.v1.RaceResultR\aresults\"\x89\x01\n" +
	"\n" +
	"RaceResult\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\tR\bplayerId\x12\x1a\n" +
	"\bposition\x18\x02 \x01(\rR\bposition\x12\"\n" +
	"\rtotal_time_ms\x18\x03 \x01(\rR\vtotalTimeMs\x12\x1e\n" +
	"\vbest_lap_ms\x18\x04 \x01(\rR\tbestLapMs\"I\n" +
	"\x12PlayerDisconnected\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\tR\bplayerId\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reasonB8Z6github.com/gustavo/racing-game-backend/protocol/gamepbb\x06proto3"

var (
	file_game_proto_rawDescOnce sync.Once
	file_game_proto_rawDescData []byte
)

func file_game_proto_rawDescGZIP() []byte {
	file_game_proto_rawDescOnce.Do(func() {
		file_game_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_game_proto_rawDesc), len(file_game_proto_rawDesc)))
	})
	return file_game_proto_rawDescData
}

var file_game_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_game_proto_goTypes = []any{
	(*Vector3)(nil),            // 0: racing.game.v1.Vector3
	(*Quaternion)(nil),         // 1: racing.game.v1.Quaternion
	(*JoinRaceRequest)(nil),    // 2: racing.game.v1.JoinRaceRequest
	(*JoinRaceResponse)(nil),   // 3: racing.game.v1.JoinRaceResponse
	(*RaceStarting)(nil),       // 4: racing.game.v1.RaceStarting
	(*RaceStarted)(nil),        // 5: racing.game.v1.RaceStarted
	(*PlayerInput)(nil),        // 6: racing.game.v1.PlayerInput
	(*CarState)(nil),           // 7: racing.game.v1.CarState
	(*WorldSnapshot)(nil),      // 8: racing.game.v1.WorldSnapshot
	(*CheckpointPassed)(nil),   // 9: racing.game.v1.CheckpointPassed
	(*LapCompleted)(nil),       // 10: racing.game.v1.LapCompleted
	(*RaceFinished)(nil),       // 11: racing.game.v1.RaceFinished
	(*RaceResult)(nil),         // 12: racing.game.v1.RaceResult
	(*PlayerDisconnected)(nil), // 13: racing.game.v1.PlayerDisconnected
}
var file_game_proto_depIdxs = []int32{
	0,  // 0: racing.game.v1.CarState.position:type_name -> racing.game.v1.Vector3
	1,  // 1: racing.game.v1.CarState.rotation:type_name -> racing.game.v1.Quaternion
	0,  // 2: racing.game.v1.CarState.velocity:type_name -> racing.game.v1.Vector3
	7,  // 3: racing.game.v1.WorldSnapshot.cars:type_name -> racing.game.v1.CarState
	12, // 4: racing.game.v1.RaceFinished.results:type_name -> racing.game.v1.RaceResult
	5,  // [5:5] is the sub-list for method output_type
	5,  // [5:5] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_game_proto_init() }
func file_game_proto_init() {
	if File_game_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_game_proto_rawDesc), len(file_game_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_game_proto_goTypes,
		DependencyIndexes: file_game_proto_depIdxs,
		MessageInfos:      file_game_proto_msgTypes,
	}.Build()
	File_game_proto = out.File
	file_game_proto_goTypes = nil
	file_game_proto_depIdxs = nil
}
